### ISSUE TITLE
Extend server responses to be more detailed

### ISSUE THREAD

**Issue by lukaskett** [martinkrivda/orienteerfeed#20]
A status change returns ...{"data":"Competitor status has been successfully changed"}...
Something like "Status changed to Active" would be more informative.

Similar for competitor update: "Competitor has been successfully updated" should be "Card changed to 1234".

**Comment by martinkrivda** [comment]
Here is a proposal for redesigning the response structure to make it more informative and consistent:
```
{
  "data": "Competitor has been successfully updated",
  "updatedFields": {
    "card": 1234,
    "name": "John Doe",
    "category": "M21"
  }
}
```

@lukaskett  Does this proposal meet your expectations?

**Comment by martinkrivda** [comment]
Somehow implemented. But I'm still not satisfied. The answers are not entirely consistent now. It will require proper response redesign in the future ...

because 2 things:

1. competitor update can update multiple fields so returning more detail in the response message does not make sense compared to the status change
2.  the answer is wrapped in the results object: { data: {}}: Merging the results layer into the top-level data key eliminates unnecessary nesting and keeps the response leaner and maybe should be better to change "message": "OK" to "status": "success", and key "message" use for friendly user response.
